save_dir: /path/to/output/experiments/2_stage
experiment_purpose: Full model training run, using the OMNISR code only
debug: false
mode: shadow
run_mode: train
lambda_lpips: 0.05
net: vgg
lpips_compute_in_fp32: true
lpips_clamp_01: true
pretrain_weights: /path/to/checkpoints/model_best.pth
train_dir: /path/to/dataset/train
val_dir: /path/to/dataset/val
batch_size: 4
validation_batch_size: 1
nepoch: 1000
optimizer: adamw
lr_scheduler: cosine_warm_restarts
lr_initial: 0.0001
weight_decay: 0.02
warmup: true
warmup_epochs: 5
lr_step_size: 50
lr_min: 5.0e-05
warmup_start_factor: 0.1
lr_gamma: 0.5
lr_T_max: 200
tresh_gradient_clipping: 1
reconstruction_loss: l2
train_workers: 2
eval_workers: 2
dataset: render_data
dino_imagenet_norm: true
tile_overlap: 128
tile_size: 896
arch: twoStageShadowFormer
norm_layer: nn.LayerNorm
embed_dim: 32
win_size: 16
token_projection: linear
token_mlp: leff
att_se: false
use_dino: true
eval_now: 5
train_ps: 512
resume: true
save_images: false
env: SF_FreqFus
checkpoint: 5
local_rank: 0
dino_name: dinov2_vitl14
tracker: !type:dict
  type:
  - basic
config_variations: null
base_file: null
lambda_id: null
lambda_bgrad: null
lambda_alpha: null
lambda_hessian: 0.02
lambda_stage: 0.5
lam_tv: 0.0001
lam_pseudo: 0.001
#dino_cache_dir_train: /path/to/dataset/train/dino
#dino_cache_dir_val:   /path/to/dataset/val/dino
